name: suraksha_setu_mobile
description: Suraksha Setu mobile app for emergency help and SOS alerts.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.0
  firebase_app_check: ^0.4.1+2
  firebase_auth: ^6.1.1
  google_sign_in: ^6.1.5
  cloud_firestore: ^6.0.3
  shared_preferences: ^2.2.3
  permission_handler: ^12.0.1
  geolocator: ^14.0.2
  volume_controller: ^2.0.3
  flutter_background_service: ^5.0.6
  flutter_background_service_android: ^6.3.1
  flutter_foreground_task: ^6.2.2
  wakelock_plus: ^1.3.2
  connectivity_plus: ^5.0.2
  path_provider: ^2.1.2
  path: ^1.9.0
  intl: ^0.19.0
  async: ^2.11.0
  camera: ^0.11.0+2
  record: ^6.2.0
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/google_logo.png
