name: suraksha_setu_mobile
description: Suraksha Setu mobile app for emergency help and SOS alerts.
publish_to: 'none' # since this isn't a public package

version: 1.0.0+1

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.0
  firebase_auth: ^4.15.0
  google_sign_in: ^6.1.5
  cloud_firestore: ^4.8.0
  shared_preferences: ^2.2.3
  permission_handler: ^11.0.1
  geolocator: ^14.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/google_logo.png
